#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.StokModul
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbStok")]
	public partial class StokDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_GRUPLAR(TBL_GRUPLAR instance);
    partial void UpdateTBL_GRUPLAR(TBL_GRUPLAR instance);
    partial void DeleteTBL_GRUPLAR(TBL_GRUPLAR instance);
    partial void InsertTBL_STOKLAR(TBL_STOKLAR instance);
    partial void UpdateTBL_STOKLAR(TBL_STOKLAR instance);
    partial void DeleteTBL_STOKLAR(TBL_STOKLAR instance);
    #endregion
		
		public StokDatabaseDataContext() : 
				base(global::Otomasyon.Properties.Settings.Default.DbStokConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_GRUPLAR> TBL_GRUPLAR
		{
			get
			{
				return this.GetTable<TBL_GRUPLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STOKLAR> TBL_STOKLAR
		{
			get
			{
				return this.GetTable<TBL_STOKLAR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_GRUPLAR")]
	public partial class TBL_GRUPLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GRUPID;
		
		private string _GRUPADI;
		
		private string _GRUPKODU;
		
		private System.Nullable<System.DateTime> _GRUPSAVEDATE;
		
		private System.Nullable<int> _GRUPSAVEUSER;
		
		private System.Nullable<int> _GRUPEDITUSER;
		
		private System.Nullable<System.DateTime> _GRUPEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGRUPIDChanging(int value);
    partial void OnGRUPIDChanged();
    partial void OnGRUPADIChanging(string value);
    partial void OnGRUPADIChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnGRUPSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPSAVEDATEChanged();
    partial void OnGRUPSAVEUSERChanging(System.Nullable<int> value);
    partial void OnGRUPSAVEUSERChanged();
    partial void OnGRUPEDITUSERChanging(System.Nullable<int> value);
    partial void OnGRUPEDITUSERChanged();
    partial void OnGRUPEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPEDITDATEChanged();
    #endregion
		
		public TBL_GRUPLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GRUPID
		{
			get
			{
				return this._GRUPID;
			}
			set
			{
				if ((this._GRUPID != value))
				{
					this.OnGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._GRUPID = value;
					this.SendPropertyChanged("GRUPID");
					this.OnGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADI", DbType="NVarChar(30)")]
		public string GRUPADI
		{
			get
			{
				return this._GRUPADI;
			}
			set
			{
				if ((this._GRUPADI != value))
				{
					this.OnGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._GRUPADI = value;
					this.SendPropertyChanged("GRUPADI");
					this.OnGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NVarChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPSAVEDATE
		{
			get
			{
				return this._GRUPSAVEDATE;
			}
			set
			{
				if ((this._GRUPSAVEDATE != value))
				{
					this.OnGRUPSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEDATE = value;
					this.SendPropertyChanged("GRUPSAVEDATE");
					this.OnGRUPSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEUSER", DbType="Int")]
		public System.Nullable<int> GRUPSAVEUSER
		{
			get
			{
				return this._GRUPSAVEUSER;
			}
			set
			{
				if ((this._GRUPSAVEUSER != value))
				{
					this.OnGRUPSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEUSER = value;
					this.SendPropertyChanged("GRUPSAVEUSER");
					this.OnGRUPSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDITUSER", DbType="Int")]
		public System.Nullable<int> GRUPEDITUSER
		{
			get
			{
				return this._GRUPEDITUSER;
			}
			set
			{
				if ((this._GRUPEDITUSER != value))
				{
					this.OnGRUPEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDITUSER = value;
					this.SendPropertyChanged("GRUPEDITUSER");
					this.OnGRUPEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPEDITDATE
		{
			get
			{
				return this._GRUPEDITDATE;
			}
			set
			{
				if ((this._GRUPEDITDATE != value))
				{
					this.OnGRUPEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDITDATE = value;
					this.SendPropertyChanged("GRUPEDITDATE");
					this.OnGRUPEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKLAR")]
	public partial class TBL_STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STOKID;
		
		private string _STOKBARKOD;
		
		private string _STOKKODU;
		
		private string _STOKADI;
		
		private string _STOKBIRIM;
		
		private System.Nullable<decimal> _STOKSATISFIYAT;
		
		private System.Nullable<decimal> _STOKALISFIYAT;
		
		private System.Nullable<decimal> _STOKKDV;
		
		private System.Nullable<int> _STOKGRUPID;
		
		private System.Data.Linq.Binary _STOKRESIM;
		
		private System.Nullable<int> _STOKSAVEUSER;
		
		private System.Nullable<System.DateTime> _STOKSAVEDATE;
		
		private System.Nullable<int> _STOKEDITUSER;
		
		private System.Nullable<System.DateTime> _STOKEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTOKIDChanging(int value);
    partial void OnSTOKIDChanged();
    partial void OnSTOKBARKODChanging(string value);
    partial void OnSTOKBARKODChanged();
    partial void OnSTOKKODUChanging(string value);
    partial void OnSTOKKODUChanged();
    partial void OnSTOKADIChanging(string value);
    partial void OnSTOKADIChanged();
    partial void OnSTOKBIRIMChanging(string value);
    partial void OnSTOKBIRIMChanged();
    partial void OnSTOKSATISFIYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATISFIYATChanged();
    partial void OnSTOKALISFIYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKALISFIYATChanged();
    partial void OnSTOKKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKKDVChanged();
    partial void OnSTOKGRUPIDChanging(System.Nullable<int> value);
    partial void OnSTOKGRUPIDChanged();
    partial void OnSTOKRESIMChanging(System.Data.Linq.Binary value);
    partial void OnSTOKRESIMChanged();
    partial void OnSTOKSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSTOKSAVEUSERChanged();
    partial void OnSTOKSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKSAVEDATEChanged();
    partial void OnSTOKEDITUSERChanging(System.Nullable<int> value);
    partial void OnSTOKEDITUSERChanged();
    partial void OnSTOKEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKEDITDATEChanged();
    #endregion
		
		public TBL_STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STOKID
		{
			get
			{
				return this._STOKID;
			}
			set
			{
				if ((this._STOKID != value))
				{
					this.OnSTOKIDChanging(value);
					this.SendPropertyChanging();
					this._STOKID = value;
					this.SendPropertyChanged("STOKID");
					this.OnSTOKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBARKOD", DbType="NVarChar(20)")]
		public string STOKBARKOD
		{
			get
			{
				return this._STOKBARKOD;
			}
			set
			{
				if ((this._STOKBARKOD != value))
				{
					this.OnSTOKBARKODChanging(value);
					this.SendPropertyChanging();
					this._STOKBARKOD = value;
					this.SendPropertyChanged("STOKBARKOD");
					this.OnSTOKBARKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKODU", DbType="NVarChar(20)")]
		public string STOKKODU
		{
			get
			{
				return this._STOKKODU;
			}
			set
			{
				if ((this._STOKKODU != value))
				{
					this.OnSTOKKODUChanging(value);
					this.SendPropertyChanging();
					this._STOKKODU = value;
					this.SendPropertyChanged("STOKKODU");
					this.OnSTOKKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADI", DbType="NVarChar(50)")]
		public string STOKADI
		{
			get
			{
				return this._STOKADI;
			}
			set
			{
				if ((this._STOKADI != value))
				{
					this.OnSTOKADIChanging(value);
					this.SendPropertyChanging();
					this._STOKADI = value;
					this.SendPropertyChanged("STOKADI");
					this.OnSTOKADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBIRIM", DbType="NVarChar(15)")]
		public string STOKBIRIM
		{
			get
			{
				return this._STOKBIRIM;
			}
			set
			{
				if ((this._STOKBIRIM != value))
				{
					this.OnSTOKBIRIMChanging(value);
					this.SendPropertyChanging();
					this._STOKBIRIM = value;
					this.SendPropertyChanged("STOKBIRIM");
					this.OnSTOKBIRIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATISFIYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATISFIYAT
		{
			get
			{
				return this._STOKSATISFIYAT;
			}
			set
			{
				if ((this._STOKSATISFIYAT != value))
				{
					this.OnSTOKSATISFIYATChanging(value);
					this.SendPropertyChanging();
					this._STOKSATISFIYAT = value;
					this.SendPropertyChanged("STOKSATISFIYAT");
					this.OnSTOKSATISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALISFIYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALISFIYAT
		{
			get
			{
				return this._STOKALISFIYAT;
			}
			set
			{
				if ((this._STOKALISFIYAT != value))
				{
					this.OnSTOKALISFIYATChanging(value);
					this.SendPropertyChanging();
					this._STOKALISFIYAT = value;
					this.SendPropertyChanged("STOKALISFIYAT");
					this.OnSTOKALISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKKDV
		{
			get
			{
				return this._STOKKDV;
			}
			set
			{
				if ((this._STOKKDV != value))
				{
					this.OnSTOKKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKKDV = value;
					this.SendPropertyChanged("STOKKDV");
					this.OnSTOKKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKGRUPID", DbType="Int")]
		public System.Nullable<int> STOKGRUPID
		{
			get
			{
				return this._STOKGRUPID;
			}
			set
			{
				if ((this._STOKGRUPID != value))
				{
					this.OnSTOKGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._STOKGRUPID = value;
					this.SendPropertyChanged("STOKGRUPID");
					this.OnSTOKGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKRESIM", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary STOKRESIM
		{
			get
			{
				return this._STOKRESIM;
			}
			set
			{
				if ((this._STOKRESIM != value))
				{
					this.OnSTOKRESIMChanging(value);
					this.SendPropertyChanging();
					this._STOKRESIM = value;
					this.SendPropertyChanged("STOKRESIM");
					this.OnSTOKRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEUSER", DbType="Int")]
		public System.Nullable<int> STOKSAVEUSER
		{
			get
			{
				return this._STOKSAVEUSER;
			}
			set
			{
				if ((this._STOKSAVEUSER != value))
				{
					this.OnSTOKSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEUSER = value;
					this.SendPropertyChanged("STOKSAVEUSER");
					this.OnSTOKSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKSAVEDATE
		{
			get
			{
				return this._STOKSAVEDATE;
			}
			set
			{
				if ((this._STOKSAVEDATE != value))
				{
					this.OnSTOKSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEDATE = value;
					this.SendPropertyChanged("STOKSAVEDATE");
					this.OnSTOKSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDITUSER", DbType="Int")]
		public System.Nullable<int> STOKEDITUSER
		{
			get
			{
				return this._STOKEDITUSER;
			}
			set
			{
				if ((this._STOKEDITUSER != value))
				{
					this.OnSTOKEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKEDITUSER = value;
					this.SendPropertyChanged("STOKEDITUSER");
					this.OnSTOKEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKEDITDATE
		{
			get
			{
				return this._STOKEDITDATE;
			}
			set
			{
				if ((this._STOKEDITDATE != value))
				{
					this.OnSTOKEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKEDITDATE = value;
					this.SendPropertyChanged("STOKEDITDATE");
					this.OnSTOKEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
