#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbStok")]
	public partial class StokDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_GRUPLAR(TBL_GRUPLAR instance);
    partial void UpdateTBL_GRUPLAR(TBL_GRUPLAR instance);
    partial void DeleteTBL_GRUPLAR(TBL_GRUPLAR instance);
    partial void InsertTBL_STOKLAR(TBL_STOKLAR instance);
    partial void UpdateTBL_STOKLAR(TBL_STOKLAR instance);
    partial void DeleteTBL_STOKLAR(TBL_STOKLAR instance);
    partial void InsertTBL_CARIGRUPLAR(TBL_CARIGRUPLAR instance);
    partial void UpdateTBL_CARIGRUPLAR(TBL_CARIGRUPLAR instance);
    partial void DeleteTBL_CARIGRUPLAR(TBL_CARIGRUPLAR instance);
    partial void InsertTBL_CARILER(TBL_CARILER instance);
    partial void UpdateTBL_CARILER(TBL_CARILER instance);
    partial void DeleteTBL_CARILER(TBL_CARILER instance);
    #endregion
		
		public StokDatabaseDataContext() : 
				base(global::Otomasyon.Properties.Settings.Default.DbStokConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_GRUPLAR> TBL_GRUPLAR
		{
			get
			{
				return this.GetTable<TBL_GRUPLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STOKLAR> TBL_STOKLAR
		{
			get
			{
				return this.GetTable<TBL_STOKLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARIGRUPLAR> TBL_CARIGRUPLAR
		{
			get
			{
				return this.GetTable<TBL_CARIGRUPLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARILER> TBL_CARILER
		{
			get
			{
				return this.GetTable<TBL_CARILER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_GRUPLAR")]
	public partial class TBL_GRUPLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GRUPID;
		
		private string _GRUPADI;
		
		private string _GRUPKODU;
		
		private System.Nullable<System.DateTime> _GRUPSAVEDATE;
		
		private System.Nullable<int> _GRUPSAVEUSER;
		
		private System.Nullable<int> _GRUPEDITUSER;
		
		private System.Nullable<System.DateTime> _GRUPEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGRUPIDChanging(int value);
    partial void OnGRUPIDChanged();
    partial void OnGRUPADIChanging(string value);
    partial void OnGRUPADIChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnGRUPSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPSAVEDATEChanged();
    partial void OnGRUPSAVEUSERChanging(System.Nullable<int> value);
    partial void OnGRUPSAVEUSERChanged();
    partial void OnGRUPEDITUSERChanging(System.Nullable<int> value);
    partial void OnGRUPEDITUSERChanged();
    partial void OnGRUPEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPEDITDATEChanged();
    #endregion
		
		public TBL_GRUPLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GRUPID
		{
			get
			{
				return this._GRUPID;
			}
			set
			{
				if ((this._GRUPID != value))
				{
					this.OnGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._GRUPID = value;
					this.SendPropertyChanged("GRUPID");
					this.OnGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADI", DbType="NVarChar(30)")]
		public string GRUPADI
		{
			get
			{
				return this._GRUPADI;
			}
			set
			{
				if ((this._GRUPADI != value))
				{
					this.OnGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._GRUPADI = value;
					this.SendPropertyChanged("GRUPADI");
					this.OnGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NVarChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPSAVEDATE
		{
			get
			{
				return this._GRUPSAVEDATE;
			}
			set
			{
				if ((this._GRUPSAVEDATE != value))
				{
					this.OnGRUPSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEDATE = value;
					this.SendPropertyChanged("GRUPSAVEDATE");
					this.OnGRUPSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEUSER", DbType="Int")]
		public System.Nullable<int> GRUPSAVEUSER
		{
			get
			{
				return this._GRUPSAVEUSER;
			}
			set
			{
				if ((this._GRUPSAVEUSER != value))
				{
					this.OnGRUPSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEUSER = value;
					this.SendPropertyChanged("GRUPSAVEUSER");
					this.OnGRUPSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDITUSER", DbType="Int")]
		public System.Nullable<int> GRUPEDITUSER
		{
			get
			{
				return this._GRUPEDITUSER;
			}
			set
			{
				if ((this._GRUPEDITUSER != value))
				{
					this.OnGRUPEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDITUSER = value;
					this.SendPropertyChanged("GRUPEDITUSER");
					this.OnGRUPEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPEDITDATE
		{
			get
			{
				return this._GRUPEDITDATE;
			}
			set
			{
				if ((this._GRUPEDITDATE != value))
				{
					this.OnGRUPEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDITDATE = value;
					this.SendPropertyChanged("GRUPEDITDATE");
					this.OnGRUPEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKLAR")]
	public partial class TBL_STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STOKID;
		
		private string _STOKBARKOD;
		
		private string _STOKKODU;
		
		private string _STOKADI;
		
		private string _STOKBIRIM;
		
		private System.Nullable<decimal> _STOKSATISFIYAT;
		
		private System.Nullable<decimal> _STOKALISFIYAT;
		
		private System.Nullable<decimal> _STOKKDV;
		
		private System.Nullable<int> _STOKGRUPID;
		
		private System.Data.Linq.Binary _STOKRESIM;
		
		private System.Nullable<int> _STOKSAVEUSER;
		
		private System.Nullable<System.DateTime> _STOKSAVEDATE;
		
		private System.Nullable<int> _STOKEDITUSER;
		
		private System.Nullable<System.DateTime> _STOKEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTOKIDChanging(int value);
    partial void OnSTOKIDChanged();
    partial void OnSTOKBARKODChanging(string value);
    partial void OnSTOKBARKODChanged();
    partial void OnSTOKKODUChanging(string value);
    partial void OnSTOKKODUChanged();
    partial void OnSTOKADIChanging(string value);
    partial void OnSTOKADIChanged();
    partial void OnSTOKBIRIMChanging(string value);
    partial void OnSTOKBIRIMChanged();
    partial void OnSTOKSATISFIYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATISFIYATChanged();
    partial void OnSTOKALISFIYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKALISFIYATChanged();
    partial void OnSTOKKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKKDVChanged();
    partial void OnSTOKGRUPIDChanging(System.Nullable<int> value);
    partial void OnSTOKGRUPIDChanged();
    partial void OnSTOKRESIMChanging(System.Data.Linq.Binary value);
    partial void OnSTOKRESIMChanged();
    partial void OnSTOKSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSTOKSAVEUSERChanged();
    partial void OnSTOKSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKSAVEDATEChanged();
    partial void OnSTOKEDITUSERChanging(System.Nullable<int> value);
    partial void OnSTOKEDITUSERChanged();
    partial void OnSTOKEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKEDITDATEChanged();
    #endregion
		
		public TBL_STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STOKID
		{
			get
			{
				return this._STOKID;
			}
			set
			{
				if ((this._STOKID != value))
				{
					this.OnSTOKIDChanging(value);
					this.SendPropertyChanging();
					this._STOKID = value;
					this.SendPropertyChanged("STOKID");
					this.OnSTOKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBARKOD", DbType="NVarChar(20)")]
		public string STOKBARKOD
		{
			get
			{
				return this._STOKBARKOD;
			}
			set
			{
				if ((this._STOKBARKOD != value))
				{
					this.OnSTOKBARKODChanging(value);
					this.SendPropertyChanging();
					this._STOKBARKOD = value;
					this.SendPropertyChanged("STOKBARKOD");
					this.OnSTOKBARKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKODU", DbType="NVarChar(20)")]
		public string STOKKODU
		{
			get
			{
				return this._STOKKODU;
			}
			set
			{
				if ((this._STOKKODU != value))
				{
					this.OnSTOKKODUChanging(value);
					this.SendPropertyChanging();
					this._STOKKODU = value;
					this.SendPropertyChanged("STOKKODU");
					this.OnSTOKKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADI", DbType="NVarChar(50)")]
		public string STOKADI
		{
			get
			{
				return this._STOKADI;
			}
			set
			{
				if ((this._STOKADI != value))
				{
					this.OnSTOKADIChanging(value);
					this.SendPropertyChanging();
					this._STOKADI = value;
					this.SendPropertyChanged("STOKADI");
					this.OnSTOKADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBIRIM", DbType="NVarChar(15)")]
		public string STOKBIRIM
		{
			get
			{
				return this._STOKBIRIM;
			}
			set
			{
				if ((this._STOKBIRIM != value))
				{
					this.OnSTOKBIRIMChanging(value);
					this.SendPropertyChanging();
					this._STOKBIRIM = value;
					this.SendPropertyChanged("STOKBIRIM");
					this.OnSTOKBIRIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATISFIYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATISFIYAT
		{
			get
			{
				return this._STOKSATISFIYAT;
			}
			set
			{
				if ((this._STOKSATISFIYAT != value))
				{
					this.OnSTOKSATISFIYATChanging(value);
					this.SendPropertyChanging();
					this._STOKSATISFIYAT = value;
					this.SendPropertyChanged("STOKSATISFIYAT");
					this.OnSTOKSATISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALISFIYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALISFIYAT
		{
			get
			{
				return this._STOKALISFIYAT;
			}
			set
			{
				if ((this._STOKALISFIYAT != value))
				{
					this.OnSTOKALISFIYATChanging(value);
					this.SendPropertyChanging();
					this._STOKALISFIYAT = value;
					this.SendPropertyChanged("STOKALISFIYAT");
					this.OnSTOKALISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKKDV
		{
			get
			{
				return this._STOKKDV;
			}
			set
			{
				if ((this._STOKKDV != value))
				{
					this.OnSTOKKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKKDV = value;
					this.SendPropertyChanged("STOKKDV");
					this.OnSTOKKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKGRUPID", DbType="Int")]
		public System.Nullable<int> STOKGRUPID
		{
			get
			{
				return this._STOKGRUPID;
			}
			set
			{
				if ((this._STOKGRUPID != value))
				{
					this.OnSTOKGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._STOKGRUPID = value;
					this.SendPropertyChanged("STOKGRUPID");
					this.OnSTOKGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKRESIM", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary STOKRESIM
		{
			get
			{
				return this._STOKRESIM;
			}
			set
			{
				if ((this._STOKRESIM != value))
				{
					this.OnSTOKRESIMChanging(value);
					this.SendPropertyChanging();
					this._STOKRESIM = value;
					this.SendPropertyChanged("STOKRESIM");
					this.OnSTOKRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEUSER", DbType="Int")]
		public System.Nullable<int> STOKSAVEUSER
		{
			get
			{
				return this._STOKSAVEUSER;
			}
			set
			{
				if ((this._STOKSAVEUSER != value))
				{
					this.OnSTOKSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEUSER = value;
					this.SendPropertyChanged("STOKSAVEUSER");
					this.OnSTOKSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKSAVEDATE
		{
			get
			{
				return this._STOKSAVEDATE;
			}
			set
			{
				if ((this._STOKSAVEDATE != value))
				{
					this.OnSTOKSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEDATE = value;
					this.SendPropertyChanged("STOKSAVEDATE");
					this.OnSTOKSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDITUSER", DbType="Int")]
		public System.Nullable<int> STOKEDITUSER
		{
			get
			{
				return this._STOKEDITUSER;
			}
			set
			{
				if ((this._STOKEDITUSER != value))
				{
					this.OnSTOKEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKEDITUSER = value;
					this.SendPropertyChanged("STOKEDITUSER");
					this.OnSTOKEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKEDITDATE
		{
			get
			{
				return this._STOKEDITDATE;
			}
			set
			{
				if ((this._STOKEDITDATE != value))
				{
					this.OnSTOKEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKEDITDATE = value;
					this.SendPropertyChanged("STOKEDITDATE");
					this.OnSTOKEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARIGRUPLAR")]
	public partial class TBL_CARIGRUPLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CARIGRUPID;
		
		private string _CARIGRUPKODU;
		
		private string _CARIGRUPADI;
		
		private System.Nullable<System.DateTime> _CARIGRUPSAVEDATE;
		
		private System.Nullable<int> _CARIGRUPSAVEUSER;
		
		private System.Nullable<System.DateTime> _CARIGRUPEDITDATE;
		
		private System.Nullable<int> _CARIGRUPEDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCARIGRUPIDChanging(int value);
    partial void OnCARIGRUPIDChanged();
    partial void OnCARIGRUPKODUChanging(string value);
    partial void OnCARIGRUPKODUChanged();
    partial void OnCARIGRUPADIChanging(string value);
    partial void OnCARIGRUPADIChanged();
    partial void OnCARIGRUPSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCARIGRUPSAVEDATEChanged();
    partial void OnCARIGRUPSAVEUSERChanging(System.Nullable<int> value);
    partial void OnCARIGRUPSAVEUSERChanged();
    partial void OnCARIGRUPEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCARIGRUPEDITDATEChanged();
    partial void OnCARIGRUPEDITUSERChanging(System.Nullable<int> value);
    partial void OnCARIGRUPEDITUSERChanged();
    #endregion
		
		public TBL_CARIGRUPLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CARIGRUPID
		{
			get
			{
				return this._CARIGRUPID;
			}
			set
			{
				if ((this._CARIGRUPID != value))
				{
					this.OnCARIGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPID = value;
					this.SendPropertyChanged("CARIGRUPID");
					this.OnCARIGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPKODU", DbType="VarChar(15)")]
		public string CARIGRUPKODU
		{
			get
			{
				return this._CARIGRUPKODU;
			}
			set
			{
				if ((this._CARIGRUPKODU != value))
				{
					this.OnCARIGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPKODU = value;
					this.SendPropertyChanged("CARIGRUPKODU");
					this.OnCARIGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPADI", DbType="VarChar(25)")]
		public string CARIGRUPADI
		{
			get
			{
				return this._CARIGRUPADI;
			}
			set
			{
				if ((this._CARIGRUPADI != value))
				{
					this.OnCARIGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPADI = value;
					this.SendPropertyChanged("CARIGRUPADI");
					this.OnCARIGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CARIGRUPSAVEDATE
		{
			get
			{
				return this._CARIGRUPSAVEDATE;
			}
			set
			{
				if ((this._CARIGRUPSAVEDATE != value))
				{
					this.OnCARIGRUPSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPSAVEDATE = value;
					this.SendPropertyChanged("CARIGRUPSAVEDATE");
					this.OnCARIGRUPSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPSAVEUSER", DbType="Int")]
		public System.Nullable<int> CARIGRUPSAVEUSER
		{
			get
			{
				return this._CARIGRUPSAVEUSER;
			}
			set
			{
				if ((this._CARIGRUPSAVEUSER != value))
				{
					this.OnCARIGRUPSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPSAVEUSER = value;
					this.SendPropertyChanged("CARIGRUPSAVEUSER");
					this.OnCARIGRUPSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CARIGRUPEDITDATE
		{
			get
			{
				return this._CARIGRUPEDITDATE;
			}
			set
			{
				if ((this._CARIGRUPEDITDATE != value))
				{
					this.OnCARIGRUPEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPEDITDATE = value;
					this.SendPropertyChanged("CARIGRUPEDITDATE");
					this.OnCARIGRUPEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPEDITUSER", DbType="Int")]
		public System.Nullable<int> CARIGRUPEDITUSER
		{
			get
			{
				return this._CARIGRUPEDITUSER;
			}
			set
			{
				if ((this._CARIGRUPEDITUSER != value))
				{
					this.OnCARIGRUPEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPEDITUSER = value;
					this.SendPropertyChanged("CARIGRUPEDITUSER");
					this.OnCARIGRUPEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARILER")]
	public partial class TBL_CARILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CARIID;
		
		private string _CARIKODU;
		
		private string _CARIADI;
		
		private string _VERGIDAIRESI;
		
		private string _VERGINO;
		
		private System.Nullable<int> _CARIGRUPID;
		
		private string _ULKE;
		
		private string _SEHIR;
		
		private string _ILCE;
		
		private string _ADRES;
		
		private string _TELEFON1;
		
		private string _TELEFON2;
		
		private string _FAX1;
		
		private string _FAX2;
		
		private string _WEBADRES;
		
		private string _MAILADRES;
		
		private string _YETKILI;
		
		private string _YETKILIMAIL;
		
		private System.Nullable<System.DateTime> _CARISAVEDATE;
		
		private System.Nullable<int> _CARISAVEUSER;
		
		private System.Nullable<System.DateTime> _CARIEDITDATE;
		
		private System.Nullable<int> _CARIEDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCARIIDChanging(int value);
    partial void OnCARIIDChanged();
    partial void OnCARIKODUChanging(string value);
    partial void OnCARIKODUChanged();
    partial void OnCARIADIChanging(string value);
    partial void OnCARIADIChanged();
    partial void OnVERGIDAIRESIChanging(string value);
    partial void OnVERGIDAIRESIChanged();
    partial void OnVERGINOChanging(string value);
    partial void OnVERGINOChanged();
    partial void OnCARIGRUPIDChanging(System.Nullable<int> value);
    partial void OnCARIGRUPIDChanged();
    partial void OnULKEChanging(string value);
    partial void OnULKEChanged();
    partial void OnSEHIRChanging(string value);
    partial void OnSEHIRChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnTELEFON1Changing(string value);
    partial void OnTELEFON1Changed();
    partial void OnTELEFON2Changing(string value);
    partial void OnTELEFON2Changed();
    partial void OnFAX1Changing(string value);
    partial void OnFAX1Changed();
    partial void OnFAX2Changing(string value);
    partial void OnFAX2Changed();
    partial void OnWEBADRESChanging(string value);
    partial void OnWEBADRESChanged();
    partial void OnMAILADRESChanging(string value);
    partial void OnMAILADRESChanged();
    partial void OnYETKILIChanging(string value);
    partial void OnYETKILIChanged();
    partial void OnYETKILIMAILChanging(string value);
    partial void OnYETKILIMAILChanged();
    partial void OnCARISAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCARISAVEDATEChanged();
    partial void OnCARISAVEUSERChanging(System.Nullable<int> value);
    partial void OnCARISAVEUSERChanged();
    partial void OnCARIEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCARIEDITDATEChanged();
    partial void OnCARIEDITUSERChanging(System.Nullable<int> value);
    partial void OnCARIEDITUSERChanged();
    #endregion
		
		public TBL_CARILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CARIID
		{
			get
			{
				return this._CARIID;
			}
			set
			{
				if ((this._CARIID != value))
				{
					this.OnCARIIDChanging(value);
					this.SendPropertyChanging();
					this._CARIID = value;
					this.SendPropertyChanged("CARIID");
					this.OnCARIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIKODU", DbType="VarChar(15)")]
		public string CARIKODU
		{
			get
			{
				return this._CARIKODU;
			}
			set
			{
				if ((this._CARIKODU != value))
				{
					this.OnCARIKODUChanging(value);
					this.SendPropertyChanging();
					this._CARIKODU = value;
					this.SendPropertyChanged("CARIKODU");
					this.OnCARIKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIADI", DbType="VarChar(25)")]
		public string CARIADI
		{
			get
			{
				return this._CARIADI;
			}
			set
			{
				if ((this._CARIADI != value))
				{
					this.OnCARIADIChanging(value);
					this.SendPropertyChanging();
					this._CARIADI = value;
					this.SendPropertyChanged("CARIADI");
					this.OnCARIADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGIDAIRESI", DbType="VarChar(50)")]
		public string VERGIDAIRESI
		{
			get
			{
				return this._VERGIDAIRESI;
			}
			set
			{
				if ((this._VERGIDAIRESI != value))
				{
					this.OnVERGIDAIRESIChanging(value);
					this.SendPropertyChanging();
					this._VERGIDAIRESI = value;
					this.SendPropertyChanged("VERGIDAIRESI");
					this.OnVERGIDAIRESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGINO", DbType="VarChar(25)")]
		public string VERGINO
		{
			get
			{
				return this._VERGINO;
			}
			set
			{
				if ((this._VERGINO != value))
				{
					this.OnVERGINOChanging(value);
					this.SendPropertyChanging();
					this._VERGINO = value;
					this.SendPropertyChanged("VERGINO");
					this.OnVERGINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIGRUPID", DbType="Int")]
		public System.Nullable<int> CARIGRUPID
		{
			get
			{
				return this._CARIGRUPID;
			}
			set
			{
				if ((this._CARIGRUPID != value))
				{
					this.OnCARIGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._CARIGRUPID = value;
					this.SendPropertyChanged("CARIGRUPID");
					this.OnCARIGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULKE", DbType="VarChar(50)")]
		public string ULKE
		{
			get
			{
				return this._ULKE;
			}
			set
			{
				if ((this._ULKE != value))
				{
					this.OnULKEChanging(value);
					this.SendPropertyChanging();
					this._ULKE = value;
					this.SendPropertyChanged("ULKE");
					this.OnULKEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEHIR", DbType="VarChar(50)")]
		public string SEHIR
		{
			get
			{
				return this._SEHIR;
			}
			set
			{
				if ((this._SEHIR != value))
				{
					this.OnSEHIRChanging(value);
					this.SendPropertyChanging();
					this._SEHIR = value;
					this.SendPropertyChanged("SEHIR");
					this.OnSEHIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="VarChar(50)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON1", DbType="VarChar(16)")]
		public string TELEFON1
		{
			get
			{
				return this._TELEFON1;
			}
			set
			{
				if ((this._TELEFON1 != value))
				{
					this.OnTELEFON1Changing(value);
					this.SendPropertyChanging();
					this._TELEFON1 = value;
					this.SendPropertyChanged("TELEFON1");
					this.OnTELEFON1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON2", DbType="VarChar(16)")]
		public string TELEFON2
		{
			get
			{
				return this._TELEFON2;
			}
			set
			{
				if ((this._TELEFON2 != value))
				{
					this.OnTELEFON2Changing(value);
					this.SendPropertyChanging();
					this._TELEFON2 = value;
					this.SendPropertyChanged("TELEFON2");
					this.OnTELEFON2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX1", DbType="VarChar(16)")]
		public string FAX1
		{
			get
			{
				return this._FAX1;
			}
			set
			{
				if ((this._FAX1 != value))
				{
					this.OnFAX1Changing(value);
					this.SendPropertyChanging();
					this._FAX1 = value;
					this.SendPropertyChanged("FAX1");
					this.OnFAX1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX2", DbType="VarChar(16)")]
		public string FAX2
		{
			get
			{
				return this._FAX2;
			}
			set
			{
				if ((this._FAX2 != value))
				{
					this.OnFAX2Changing(value);
					this.SendPropertyChanging();
					this._FAX2 = value;
					this.SendPropertyChanged("FAX2");
					this.OnFAX2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEBADRES", DbType="VarChar(50)")]
		public string WEBADRES
		{
			get
			{
				return this._WEBADRES;
			}
			set
			{
				if ((this._WEBADRES != value))
				{
					this.OnWEBADRESChanging(value);
					this.SendPropertyChanging();
					this._WEBADRES = value;
					this.SendPropertyChanged("WEBADRES");
					this.OnWEBADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAILADRES", DbType="VarChar(50)")]
		public string MAILADRES
		{
			get
			{
				return this._MAILADRES;
			}
			set
			{
				if ((this._MAILADRES != value))
				{
					this.OnMAILADRESChanging(value);
					this.SendPropertyChanging();
					this._MAILADRES = value;
					this.SendPropertyChanged("MAILADRES");
					this.OnMAILADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILI", DbType="VarChar(30)")]
		public string YETKILI
		{
			get
			{
				return this._YETKILI;
			}
			set
			{
				if ((this._YETKILI != value))
				{
					this.OnYETKILIChanging(value);
					this.SendPropertyChanging();
					this._YETKILI = value;
					this.SendPropertyChanged("YETKILI");
					this.OnYETKILIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILIMAIL", DbType="VarChar(50)")]
		public string YETKILIMAIL
		{
			get
			{
				return this._YETKILIMAIL;
			}
			set
			{
				if ((this._YETKILIMAIL != value))
				{
					this.OnYETKILIMAILChanging(value);
					this.SendPropertyChanging();
					this._YETKILIMAIL = value;
					this.SendPropertyChanged("YETKILIMAIL");
					this.OnYETKILIMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARISAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CARISAVEDATE
		{
			get
			{
				return this._CARISAVEDATE;
			}
			set
			{
				if ((this._CARISAVEDATE != value))
				{
					this.OnCARISAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._CARISAVEDATE = value;
					this.SendPropertyChanged("CARISAVEDATE");
					this.OnCARISAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARISAVEUSER", DbType="Int")]
		public System.Nullable<int> CARISAVEUSER
		{
			get
			{
				return this._CARISAVEUSER;
			}
			set
			{
				if ((this._CARISAVEUSER != value))
				{
					this.OnCARISAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._CARISAVEUSER = value;
					this.SendPropertyChanged("CARISAVEUSER");
					this.OnCARISAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CARIEDITDATE
		{
			get
			{
				return this._CARIEDITDATE;
			}
			set
			{
				if ((this._CARIEDITDATE != value))
				{
					this.OnCARIEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._CARIEDITDATE = value;
					this.SendPropertyChanged("CARIEDITDATE");
					this.OnCARIEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIEDITUSER", DbType="Int")]
		public System.Nullable<int> CARIEDITUSER
		{
			get
			{
				return this._CARIEDITUSER;
			}
			set
			{
				if ((this._CARIEDITUSER != value))
				{
					this.OnCARIEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._CARIEDITUSER = value;
					this.SendPropertyChanged("CARIEDITUSER");
					this.OnCARIEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
