<?xml version="1.0" encoding="utf-8"?><Database Name="DbStok" Class="StokDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-SDVHSF8\SQLEXPRESS;Initial Catalog=DbStok;Integrated Security=True" SettingsObjectName="Otomasyon.Properties.Settings" SettingsPropertyName="DbStokConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_GRUPLAR" Member="TBL_GRUPLAR">
    <Type Name="TBL_GRUPLAR">
      <Column Name="GRUPID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GRUPADI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GRUPKODU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GRUPSAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GRUPSAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRUPEDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRUPEDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STOKLAR" Member="TBL_STOKLAR">
    <Type Name="TBL_STOKLAR">
      <Column Name="STOKID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STOKBARKOD" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="STOKKODU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="STOKADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STOKBIRIM" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="STOKSATISFIYAT" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="STOKALISFIYAT" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="STOKKDV" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="STOKGRUPID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOKRESIM" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="STOKSAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOKSAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STOKEDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOKEDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CARIGRUPLAR" Member="TBL_CARIGRUPLAR">
    <Type Name="TBL_CARIGRUPLAR">
      <Column Name="CARIGRUPID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CARIGRUPKODU" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CARIGRUPADI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CARIGRUPSAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CARIGRUPSAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIGRUPEDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CARIGRUPEDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CARILER" Member="TBL_CARILER">
    <Type Name="TBL_CARILER">
      <Column Name="CARIID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CARIKODU" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CARIADI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="VERGIDAIRESI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VERGINO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CARIGRUPID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ULKE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SEHIR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ILCE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADRES" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TELEFON1" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="TELEFON2" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="FAX1" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="FAX2" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="WEBADRES" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MAILADRES" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="YETKILI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="YETKILIMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CARISAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CARISAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIEDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CARIEDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_KASAHAREKETLERI" Member="TBL_KASAHAREKETLERI">
    <Type Name="TBL_KASAHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KASAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GCKODU" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TUTAR" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_KASALAR" Member="TBL_KASALAR">
    <Type Name="TBL_KASALAR">
      <Column Name="KASAID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KASAKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="KASAADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CARIHAREKETLERI" Member="TBL_CARIHAREKETLERI">
    <Type Name="TBL_CARIHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BORC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ALACAK" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIP" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KASAHAREKETLERI" Member="VW_KASAHAREKETLERI">
    <Type Name="VW_KASAHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KASAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KASAKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="KASAADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CARIKODU" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CARIADI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KASADURUM" Member="VW_KASADURUM">
    <Type Name="VW_KASADURUM">
      <Column Name="KASAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="BAKIYE" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KASALISTESI" Member="VW_KASALISTESI">
    <Type Name="VW_KASALISTESI">
      <Column Name="KASAID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KASAKODU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="KASAADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="BAKIYE" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BANKAHAREKETLERI" Member="TBL_BANKAHAREKETLERI">
    <Type Name="TBL_BANKAHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BANKAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GCKODU" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TUTAR" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BANKALAR" Member="TBL_BANKALAR">
    <Type Name="TBL_BANKALAR">
      <Column Name="BANKAID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HESAPNO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BANKAADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HESAPADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SUBE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TEL" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="ADRES" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TEMSILCI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TEMSILCIMAIL" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="SAVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAVEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDITUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_BANKADURUM" Member="VW_BANKADURUM">
    <Type Name="VW_BANKADURUM">
      <Column Name="BANKAID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="BAKIYE" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_BANKALISTESI" Member="VW_BANKALISTESI">
    <Type Name="VW_BANKALISTESI">
      <Column Name="BANKAID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HESAPNO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BANKAADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HESAPADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="BAKIYE" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_BANKAHAREKETLERI" Member="VW_BANKAHAREKETLERI">
    <Type Name="VW_BANKAHAREKETLERI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BANKAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BELGENO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TARIH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVRAKTURU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EVRAKID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TUTAR" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ACIKLAMA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GIRIS" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CIKIS" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HESAPNO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HESAPADI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>